- name: CycloneDX Node.js Generate SBOM
  # You may pin to the exact commit or the version.
  # uses: CycloneDX/gh-node-module-generatebom@b5753d516608ed84f7a40eb19b7687b5828b9b2d
  uses: CycloneDX/gh-node-module-generatebom@v1.0.0
  with:
    # The path to a Node.js project
    path: # optional, default is ./
    # Output filename
    output: # optional, default is ./bom.xml
